import 'dart:convert';
import 'dart:io';

void main(List<String> args) async {
  final inputPath = args.isNotEmpty ? args[0] : 'tool/attributes.json';
  final inputFile = File(inputPath);

  if (!inputFile.existsSync()) {
    stderr.writeln('Error: Input file "$inputPath" not found.');
    exit(1);
  }

  print('Reading $inputPath...');
  final content = await inputFile.readAsString();
  final List<dynamic> jsonList = json.decode(content) as List<dynamic>;
  print('Loaded ${jsonList.length} attributes from JSON.');

  final exactEntries = <Map<String, String>>[];
  final wildcardEntries = <Map<String, String>>[];

  for (final item in jsonList) {
    final map = item as Map<String, dynamic>;
    final tag = (map['tag'] as String? ?? '').trim();
    final name = (map['name'] as String? ?? '').trim();
    final keyword = (map['keyword'] as String? ?? '').trim();
    final vr = (map['valueRepresentation'] as String? ?? 'UN').trim();
    final vm = (map['valueMultiplicity'] as String? ?? '1').trim();
    final retired = (map['retired'] as String? ?? 'N').trim();
    final id = (map['id'] as String? ?? '').trim().toUpperCase();

    if (id.isEmpty) continue;

    final entry = {
      'tag': tag,
      'name': name,
      'keyword': keyword,
      'valueRepresentation': vr,
      'valueMultiplicity': vm,
      'retired': retired,
      'id': id,
    };

    if (id.contains('X')) {
      wildcardEntries.add(entry);
    } else {
      exactEntries.add(entry);
    }
  }

  print(
      'Found ${exactEntries.length} exact tags, ${wildcardEntries.length} wildcard tags.');

  final buffer = StringBuffer();
  buffer.writeln('// GENERATED CODE - DO NOT MODIFY BY HAND');
  buffer.writeln('// Generated by tool/generate_dicom_dictionary.dart');
  buffer.writeln(
      '// Source: standard/attributes.json (innolitics/dicom-standard)');
  buffer.writeln();
  buffer.writeln("import 'dicom_tag_info.dart';");
  buffer.writeln();
  buffer.writeln(
      '/// Comprehensive DICOM Data Dictionary containing standard Part 6 attributes,');
  buffer
      .writeln('/// repeating groups (wildcards), and private tag resolution.');
  buffer.writeln('class DicomDictionary {');
  buffer.writeln(
      '  /// Total count of unique standard exact tags in dictionary.');
  buffer.writeln('  static int get standardTagCount => _exactTags.length;');
  buffer.writeln();
  buffer.writeln(
      '  /// Looks up a tag by standard tag format "(GGGG,EEEE)" or 8-char hex ID "GGGGEEEE".');
  buffer.writeln(
      '  /// If tag is private (odd group), synthesizes a Private Tag DicomTagInfo.');
  buffer
      .writeln('  static DicomTagInfo lookup(String tagOrId, {String? vr}) {');
  buffer.writeln("    final normalized = normalizeTagId(tagOrId);");
  buffer.writeln('    if (normalized.length != 8) {');
  buffer.writeln('      final formatted = formatTag(tagOrId);');
  buffer.writeln("      return DicomTagInfo(");
  buffer.writeln("        tag: formatted,");
  buffer.writeln("        name: 'Invalid Tag',");
  buffer.writeln("        keyword: 'InvalidTag',");
  buffer.writeln("        valueRepresentation: vr ?? 'UN',");
  buffer.writeln("        valueMultiplicity: '1',");
  buffer.writeln("        retired: 'N',");
  buffer.writeln("        id: normalized,");
  buffer.writeln("      );");
  buffer.writeln('    }');
  buffer.writeln();
  buffer.writeln('    // 1. Direct O(1) lookup');
  buffer.writeln('    final exact = _exactTags[normalized];');
  buffer.writeln('    if (exact != null) {');
  buffer
      .writeln('      if (vr != null && exact.valueRepresentation == "UN") {');
  buffer.writeln('        return DicomTagInfo(');
  buffer.writeln('          tag: exact.tag,');
  buffer.writeln('          name: exact.name,');
  buffer.writeln('          keyword: exact.keyword,');
  buffer.writeln('          valueRepresentation: vr,');
  buffer.writeln('          valueMultiplicity: exact.valueMultiplicity,');
  buffer.writeln('          retired: exact.retired,');
  buffer.writeln('          id: exact.id,');
  buffer.writeln('        );');
  buffer.writeln('      }');
  buffer.writeln('      return exact;');
  buffer.writeln('    }');
  buffer.writeln();
  buffer.writeln('    // 2. Wildcard / Repeating Group check');
  buffer.writeln('    final wildcard = _lookupWildcard(normalized, vr: vr);');
  buffer.writeln('    if (wildcard != null) return wildcard;');
  buffer.writeln();
  buffer.writeln('    // 3. Check for Private Tag (Odd group number)');
  buffer.writeln(
      '    final group = int.tryParse(normalized.substring(0, 4), radix: 16);');
  buffer.writeln(
      '    final element = int.tryParse(normalized.substring(4, 8), radix: 16);');
  buffer.writeln('    if (group != null && group.isOdd) {');
  buffer.writeln(
      '      final isCreator = element != null && element >= 0x0010 && element <= 0x00FF;');
  buffer.writeln('      return DicomTagInfo(');
  buffer.writeln(
      "        tag: '(\${normalized.substring(0, 4)},\${normalized.substring(4)})',");
  buffer
      .writeln("        name: isCreator ? 'Private Creator' : 'Private Tag',");
  buffer
      .writeln("        keyword: isCreator ? 'PrivateCreator' : 'PrivateTag',");
  buffer
      .writeln("        valueRepresentation: vr ?? (isCreator ? 'LO' : 'UN'),");
  buffer.writeln("        valueMultiplicity: '1',");
  buffer.writeln("        retired: 'N',");
  buffer.writeln('        id: normalized,');
  buffer.writeln('        isPrivate: true,');
  buffer.writeln('      );');
  buffer.writeln('    }');
  buffer.writeln();
  buffer.writeln('    // 4. Unknown Standard Tag fallback');
  buffer.writeln('    return DicomTagInfo(');
  buffer.writeln(
      "      tag: '(\${normalized.substring(0, 4)},\${normalized.substring(4)})',");
  buffer.writeln("      name: 'Unknown Tag',");
  buffer.writeln("      keyword: 'UnknownTag',");
  buffer.writeln("      valueRepresentation: vr ?? 'UN',");
  buffer.writeln("      valueMultiplicity: '1',");
  buffer.writeln("      retired: 'N',");
  buffer.writeln('      id: normalized,');
  buffer.writeln('      isPrivate: false,');
  buffer.writeln('    );');
  buffer.writeln('  }');
  buffer.writeln();
  buffer.writeln(
      '  /// Normalizes a tag string into an 8-character uppercase hex string.');
  buffer.writeln('  static String normalizeTagId(String tag) {');
  buffer.writeln(
      "    return tag.replaceAll(RegExp(r'[^0-9A-Fa-f]'), '').toUpperCase();");
  buffer.writeln('  }');
  buffer.writeln();
  buffer.writeln(
      '  /// Formats an 8-character hex string into standard "(GGGG,EEEE)" format.');
  buffer.writeln('  static String formatTag(String tagOrId) {');
  buffer.writeln('    final norm = normalizeTagId(tagOrId);');
  buffer.writeln('    if (norm.length == 8) {');
  buffer.writeln(
      "      return '(\${norm.substring(0, 4)},\${norm.substring(4)})';");
  buffer.writeln('    }');
  buffer.writeln('    return tagOrId;');
  buffer.writeln('  }');
  buffer.writeln();
  buffer.writeln(
      '  static DicomTagInfo? _lookupWildcard(String normalized, {String? vr}) {');
  buffer.writeln('    for (final entry in _wildcardEntries) {');
  buffer.writeln('      if (entry.matches(normalized)) {');
  buffer.writeln('        return DicomTagInfo(');
  buffer.writeln(
      "          tag: '(\${normalized.substring(0, 4)},\${normalized.substring(4)})',");
  buffer.writeln('          name: entry.name,');
  buffer.writeln('          keyword: entry.keyword,');
  buffer.writeln(
      '          valueRepresentation: vr ?? entry.valueRepresentation,');
  buffer.writeln('          valueMultiplicity: entry.valueMultiplicity,');
  buffer.writeln('          retired: entry.retired,');
  buffer.writeln('          id: normalized,');
  buffer.writeln('        );');
  buffer.writeln('      }');
  buffer.writeln('    }');
  buffer.writeln('    return null;');
  buffer.writeln('  }');
  buffer.writeln();
  buffer.writeln('  static final List<_WildcardPattern> _wildcardEntries = [');
  for (final w in wildcardEntries) {
    final patternId = w['id']!;
    final regexStr = patternId.replaceAll('X', '[0-9A-Fa-f]');
    final safeName = _escapeString(w['name']!);
    final safeKeyword = _escapeString(w['keyword']!);
    final safeVr = _escapeString(w['valueRepresentation']!);
    final safeVm = _escapeString(w['valueMultiplicity']!);
    final safeRet = _escapeString(w['retired']!);
    buffer.writeln(
        "    _WildcardPattern(RegExp(r'^$regexStr\$'), '$safeName', '$safeKeyword', '$safeVr', '$safeVm', '$safeRet'),");
  }
  buffer.writeln('  ];');
  buffer.writeln();
  buffer.writeln('  static const Map<String, DicomTagInfo> _exactTags = {');
  for (final e in exactEntries) {
    final id = e['id']!;
    final tag = _escapeString(e['tag']!);
    final name = _escapeString(e['name']!);
    final keyword = _escapeString(e['keyword']!);
    final vr = _escapeString(e['valueRepresentation']!);
    final vm = _escapeString(e['valueMultiplicity']!);
    final ret = _escapeString(e['retired']!);
    buffer.writeln(
        "    '$id': DicomTagInfo(tag: '$tag', name: '$name', keyword: '$keyword', valueRepresentation: '$vr', valueMultiplicity: '$vm', retired: '$ret', id: '$id'),");
  }
  buffer.writeln('  };');
  buffer.writeln('}');
  buffer.writeln();
  buffer.writeln('class _WildcardPattern {');
  buffer.writeln('  final RegExp pattern;');
  buffer.writeln('  final String name;');
  buffer.writeln('  final String keyword;');
  buffer.writeln('  final String valueRepresentation;');
  buffer.writeln('  final String valueMultiplicity;');
  buffer.writeln('  final String retired;');
  buffer.writeln(
      '  const _WildcardPattern(this.pattern, this.name, this.keyword, this.valueRepresentation, this.valueMultiplicity, this.retired);');
  buffer.writeln('  bool matches(String id) => pattern.hasMatch(id);');
  buffer.writeln('}');

  final outputPath = 'lib/src/dictionary/dicom_dictionary.g.dart';
  final outputFile = File(outputPath);
  await outputFile.parent.create(recursive: true);
  await outputFile.writeAsString(buffer.toString());
  print(
      'Successfully generated $outputPath (${outputFile.lengthSync()} bytes).');
}

String _escapeString(String str) {
  return str
      .replaceAll(r'\', r'\\')
      .replaceAll("'", r"\'")
      .replaceAll(r'$', r'\$');
}
